CREATE TABLE IF NOT EXISTS guilds (
  id INTEGER PRIMARY KEY,
  filter INTEGER NOT NULL DEFAULT 0,
  volume INTEGER NOT NULL DEFAULT 100,
  auto_leave INTEGER NOT NULL DEFAULT 1,
  optional_search INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (id) REFERENCES whitelist (guild_id)
);
