CREATE TABLE IF NOT EXISTS guilds (
  id INTEGER PRIMARY KEY,
  filter INTEGER NOT NULL DEFAULT 0,
  volume INTEGER NOT NULL DEFAULT 70,
  auto_leave INTEGER NOT NULL DEFAULT 0,
  shuffle INTEGER NOT NULL DEFAULT 0,
  loop INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (id) REFERENCES whitelist (guild_id)
);
